language: python
dist: xenial
python:
  - "3.7"
sudo: true
install:
  - pip install -r requirements.txt
  - python scraper/setup.py install
  - python prerender/setup.py install
script:
  - python -m unittest discover -s tests/
  - python -m pylint scraper/scraper.py prerender/prerender.py
  - coverage run --source=prerender/,scraper/  -m unittest discover -s tests/ && coverage report -m
  - codecov